FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates libgl1 libopengl0 libegl1 libfontconfig1 libdbus-1-3 libglib2.0-0 \
    weston fonts-dejavu-core && rm -rf /var/lib/apt/lists/*
